// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Document is the predicate function for document builders.
type Document func(*sql.Selector)

// DocumentRevision is the predicate function for documentrevision builders.
type DocumentRevision func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Taxonomy is the predicate function for taxonomy builders.
type Taxonomy func(*sql.Selector)

// Term is the predicate function for term builders.
type Term func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
