// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shirone-platform/backend/ent/document"
	"github.com/shirone-platform/backend/ent/documentrevision"
	"github.com/shirone-platform/backend/ent/user"
)

// DocumentRevisionCreate is the builder for creating a DocumentRevision entity.
type DocumentRevisionCreate struct {
	config
	mutation *DocumentRevisionMutation
	hooks    []Hook
}

// SetVersion sets the "version" field.
func (_c *DocumentRevisionCreate) SetVersion(v int) *DocumentRevisionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *DocumentRevisionCreate) SetKind(v string) *DocumentRevisionCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *DocumentRevisionCreate) SetSlug(v string) *DocumentRevisionCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *DocumentRevisionCreate) SetTitle(v string) *DocumentRevisionCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *DocumentRevisionCreate) SetBody(v string) *DocumentRevisionCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetExcerpt sets the "excerpt" field.
func (_c *DocumentRevisionCreate) SetExcerpt(v string) *DocumentRevisionCreate {
	_c.mutation.SetExcerpt(v)
	return _c
}

// SetNillableExcerpt sets the "excerpt" field if the given value is not nil.
func (_c *DocumentRevisionCreate) SetNillableExcerpt(v *string) *DocumentRevisionCreate {
	if v != nil {
		_c.SetExcerpt(*v)
	}
	return _c
}

// SetTermIds sets the "term_ids" field.
func (_c *DocumentRevisionCreate) SetTermIds(v []int) *DocumentRevisionCreate {
	_c.mutation.SetTermIds(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *DocumentRevisionCreate) SetMetadata(v map[string]interface{}) *DocumentRevisionCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DocumentRevisionCreate) SetStatus(v documentrevision.Status) *DocumentRevisionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DocumentRevisionCreate) SetCreatedAt(v time.Time) *DocumentRevisionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetDocumentID sets the "document" edge to the Document entity by ID.
func (_c *DocumentRevisionCreate) SetDocumentID(id int) *DocumentRevisionCreate {
	_c.mutation.SetDocumentID(id)
	return _c
}

// SetDocument sets the "document" edge to the Document entity.
func (_c *DocumentRevisionCreate) SetDocument(v *Document) *DocumentRevisionCreate {
	return _c.SetDocumentID(v.ID)
}

// SetEditorID sets the "editor" edge to the User entity by ID.
func (_c *DocumentRevisionCreate) SetEditorID(id int) *DocumentRevisionCreate {
	_c.mutation.SetEditorID(id)
	return _c
}

// SetEditor sets the "editor" edge to the User entity.
func (_c *DocumentRevisionCreate) SetEditor(v *User) *DocumentRevisionCreate {
	return _c.SetEditorID(v.ID)
}

// Mutation returns the DocumentRevisionMutation object of the builder.
func (_c *DocumentRevisionCreate) Mutation() *DocumentRevisionMutation {
	return _c.mutation
}

// Save creates the DocumentRevision in the database.
func (_c *DocumentRevisionCreate) Save(ctx context.Context) (*DocumentRevision, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DocumentRevisionCreate) SaveX(ctx context.Context) *DocumentRevision {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentRevisionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentRevisionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DocumentRevisionCreate) defaults() {
	if _, ok := _c.mutation.TermIds(); !ok {
		v := documentrevision.DefaultTermIds
		_c.mutation.SetTermIds(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := documentrevision.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DocumentRevisionCreate) check() error {
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "DocumentRevision.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := documentrevision.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "DocumentRevision.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "DocumentRevision.kind"`)}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "DocumentRevision.slug"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "DocumentRevision.title"`)}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "DocumentRevision.body"`)}
	}
	if _, ok := _c.mutation.TermIds(); !ok {
		return &ValidationError{Name: "term_ids", err: errors.New(`ent: missing required field "DocumentRevision.term_ids"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "DocumentRevision.metadata"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DocumentRevision.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := documentrevision.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DocumentRevision.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DocumentRevision.created_at"`)}
	}
	if len(_c.mutation.DocumentIDs()) == 0 {
		return &ValidationError{Name: "document", err: errors.New(`ent: missing required edge "DocumentRevision.document"`)}
	}
	if len(_c.mutation.EditorIDs()) == 0 {
		return &ValidationError{Name: "editor", err: errors.New(`ent: missing required edge "DocumentRevision.editor"`)}
	}
	return nil
}

func (_c *DocumentRevisionCreate) sqlSave(ctx context.Context) (*DocumentRevision, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DocumentRevisionCreate) createSpec() (*DocumentRevision, *sqlgraph.CreateSpec) {
	var (
		_node = &DocumentRevision{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(documentrevision.Table, sqlgraph.NewFieldSpec(documentrevision.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(documentrevision.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(documentrevision.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(documentrevision.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(documentrevision.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(documentrevision.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.Excerpt(); ok {
		_spec.SetField(documentrevision.FieldExcerpt, field.TypeString, value)
		_node.Excerpt = value
	}
	if value, ok := _c.mutation.TermIds(); ok {
		_spec.SetField(documentrevision.FieldTermIds, field.TypeJSON, value)
		_node.TermIds = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(documentrevision.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(documentrevision.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(documentrevision.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentrevision.DocumentTable,
			Columns: []string{documentrevision.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.document_revisions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EditorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentrevision.EditorTable,
			Columns: []string{documentrevision.EditorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_revisions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DocumentRevisionCreateBulk is the builder for creating many DocumentRevision entities in bulk.
type DocumentRevisionCreateBulk struct {
	config
	err      error
	builders []*DocumentRevisionCreate
}

// Save creates the DocumentRevision entities in the database.
func (_c *DocumentRevisionCreateBulk) Save(ctx context.Context) ([]*DocumentRevision, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DocumentRevision, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DocumentRevisionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DocumentRevisionCreateBulk) SaveX(ctx context.Context) []*DocumentRevision {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentRevisionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentRevisionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
