// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shirone-platform/backend/ent/document"
	"github.com/shirone-platform/backend/ent/documentrevision"
	"github.com/shirone-platform/backend/ent/predicate"
	"github.com/shirone-platform/backend/ent/user"
)

// DocumentRevisionUpdate is the builder for updating DocumentRevision entities.
type DocumentRevisionUpdate struct {
	config
	hooks    []Hook
	mutation *DocumentRevisionMutation
}

// Where appends a list predicates to the DocumentRevisionUpdate builder.
func (_u *DocumentRevisionUpdate) Where(ps ...predicate.DocumentRevision) *DocumentRevisionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetVersion sets the "version" field.
func (_u *DocumentRevisionUpdate) SetVersion(v int) *DocumentRevisionUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *DocumentRevisionUpdate) SetNillableVersion(v *int) *DocumentRevisionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *DocumentRevisionUpdate) AddVersion(v int) *DocumentRevisionUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *DocumentRevisionUpdate) SetSlug(v string) *DocumentRevisionUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *DocumentRevisionUpdate) SetNillableSlug(v *string) *DocumentRevisionUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *DocumentRevisionUpdate) SetTitle(v string) *DocumentRevisionUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DocumentRevisionUpdate) SetNillableTitle(v *string) *DocumentRevisionUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *DocumentRevisionUpdate) SetBody(v string) *DocumentRevisionUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *DocumentRevisionUpdate) SetNillableBody(v *string) *DocumentRevisionUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetExcerpt sets the "excerpt" field.
func (_u *DocumentRevisionUpdate) SetExcerpt(v string) *DocumentRevisionUpdate {
	_u.mutation.SetExcerpt(v)
	return _u
}

// SetNillableExcerpt sets the "excerpt" field if the given value is not nil.
func (_u *DocumentRevisionUpdate) SetNillableExcerpt(v *string) *DocumentRevisionUpdate {
	if v != nil {
		_u.SetExcerpt(*v)
	}
	return _u
}

// ClearExcerpt clears the value of the "excerpt" field.
func (_u *DocumentRevisionUpdate) ClearExcerpt() *DocumentRevisionUpdate {
	_u.mutation.ClearExcerpt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DocumentRevisionUpdate) SetStatus(v documentrevision.Status) *DocumentRevisionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DocumentRevisionUpdate) SetNillableStatus(v *documentrevision.Status) *DocumentRevisionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DocumentRevisionUpdate) SetCreatedAt(v time.Time) *DocumentRevisionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DocumentRevisionUpdate) SetNillableCreatedAt(v *time.Time) *DocumentRevisionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetDocumentID sets the "document" edge to the Document entity by ID.
func (_u *DocumentRevisionUpdate) SetDocumentID(id int) *DocumentRevisionUpdate {
	_u.mutation.SetDocumentID(id)
	return _u
}

// SetDocument sets the "document" edge to the Document entity.
func (_u *DocumentRevisionUpdate) SetDocument(v *Document) *DocumentRevisionUpdate {
	return _u.SetDocumentID(v.ID)
}

// SetEditorID sets the "editor" edge to the User entity by ID.
func (_u *DocumentRevisionUpdate) SetEditorID(id int) *DocumentRevisionUpdate {
	_u.mutation.SetEditorID(id)
	return _u
}

// SetEditor sets the "editor" edge to the User entity.
func (_u *DocumentRevisionUpdate) SetEditor(v *User) *DocumentRevisionUpdate {
	return _u.SetEditorID(v.ID)
}

// Mutation returns the DocumentRevisionMutation object of the builder.
func (_u *DocumentRevisionUpdate) Mutation() *DocumentRevisionMutation {
	return _u.mutation
}

// ClearDocument clears the "document" edge to the Document entity.
func (_u *DocumentRevisionUpdate) ClearDocument() *DocumentRevisionUpdate {
	_u.mutation.ClearDocument()
	return _u
}

// ClearEditor clears the "editor" edge to the User entity.
func (_u *DocumentRevisionUpdate) ClearEditor() *DocumentRevisionUpdate {
	_u.mutation.ClearEditor()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DocumentRevisionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentRevisionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DocumentRevisionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentRevisionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentRevisionUpdate) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := documentrevision.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "DocumentRevision.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := documentrevision.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DocumentRevision.status": %w`, err)}
		}
	}
	if _u.mutation.DocumentCleared() && len(_u.mutation.DocumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentRevision.document"`)
	}
	if _u.mutation.EditorCleared() && len(_u.mutation.EditorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentRevision.editor"`)
	}
	return nil
}

func (_u *DocumentRevisionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(documentrevision.Table, documentrevision.Columns, sqlgraph.NewFieldSpec(documentrevision.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(documentrevision.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(documentrevision.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(documentrevision.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(documentrevision.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(documentrevision.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Excerpt(); ok {
		_spec.SetField(documentrevision.FieldExcerpt, field.TypeString, value)
	}
	if _u.mutation.ExcerptCleared() {
		_spec.ClearField(documentrevision.FieldExcerpt, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(documentrevision.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(documentrevision.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.DocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentrevision.DocumentTable,
			Columns: []string{documentrevision.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentrevision.DocumentTable,
			Columns: []string{documentrevision.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EditorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentrevision.EditorTable,
			Columns: []string{documentrevision.EditorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EditorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentrevision.EditorTable,
			Columns: []string{documentrevision.EditorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{documentrevision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DocumentRevisionUpdateOne is the builder for updating a single DocumentRevision entity.
type DocumentRevisionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DocumentRevisionMutation
}

// SetVersion sets the "version" field.
func (_u *DocumentRevisionUpdateOne) SetVersion(v int) *DocumentRevisionUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *DocumentRevisionUpdateOne) SetNillableVersion(v *int) *DocumentRevisionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *DocumentRevisionUpdateOne) AddVersion(v int) *DocumentRevisionUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *DocumentRevisionUpdateOne) SetSlug(v string) *DocumentRevisionUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *DocumentRevisionUpdateOne) SetNillableSlug(v *string) *DocumentRevisionUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *DocumentRevisionUpdateOne) SetTitle(v string) *DocumentRevisionUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DocumentRevisionUpdateOne) SetNillableTitle(v *string) *DocumentRevisionUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *DocumentRevisionUpdateOne) SetBody(v string) *DocumentRevisionUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *DocumentRevisionUpdateOne) SetNillableBody(v *string) *DocumentRevisionUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetExcerpt sets the "excerpt" field.
func (_u *DocumentRevisionUpdateOne) SetExcerpt(v string) *DocumentRevisionUpdateOne {
	_u.mutation.SetExcerpt(v)
	return _u
}

// SetNillableExcerpt sets the "excerpt" field if the given value is not nil.
func (_u *DocumentRevisionUpdateOne) SetNillableExcerpt(v *string) *DocumentRevisionUpdateOne {
	if v != nil {
		_u.SetExcerpt(*v)
	}
	return _u
}

// ClearExcerpt clears the value of the "excerpt" field.
func (_u *DocumentRevisionUpdateOne) ClearExcerpt() *DocumentRevisionUpdateOne {
	_u.mutation.ClearExcerpt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DocumentRevisionUpdateOne) SetStatus(v documentrevision.Status) *DocumentRevisionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DocumentRevisionUpdateOne) SetNillableStatus(v *documentrevision.Status) *DocumentRevisionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DocumentRevisionUpdateOne) SetCreatedAt(v time.Time) *DocumentRevisionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DocumentRevisionUpdateOne) SetNillableCreatedAt(v *time.Time) *DocumentRevisionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetDocumentID sets the "document" edge to the Document entity by ID.
func (_u *DocumentRevisionUpdateOne) SetDocumentID(id int) *DocumentRevisionUpdateOne {
	_u.mutation.SetDocumentID(id)
	return _u
}

// SetDocument sets the "document" edge to the Document entity.
func (_u *DocumentRevisionUpdateOne) SetDocument(v *Document) *DocumentRevisionUpdateOne {
	return _u.SetDocumentID(v.ID)
}

// SetEditorID sets the "editor" edge to the User entity by ID.
func (_u *DocumentRevisionUpdateOne) SetEditorID(id int) *DocumentRevisionUpdateOne {
	_u.mutation.SetEditorID(id)
	return _u
}

// SetEditor sets the "editor" edge to the User entity.
func (_u *DocumentRevisionUpdateOne) SetEditor(v *User) *DocumentRevisionUpdateOne {
	return _u.SetEditorID(v.ID)
}

// Mutation returns the DocumentRevisionMutation object of the builder.
func (_u *DocumentRevisionUpdateOne) Mutation() *DocumentRevisionMutation {
	return _u.mutation
}

// ClearDocument clears the "document" edge to the Document entity.
func (_u *DocumentRevisionUpdateOne) ClearDocument() *DocumentRevisionUpdateOne {
	_u.mutation.ClearDocument()
	return _u
}

// ClearEditor clears the "editor" edge to the User entity.
func (_u *DocumentRevisionUpdateOne) ClearEditor() *DocumentRevisionUpdateOne {
	_u.mutation.ClearEditor()
	return _u
}

// Where appends a list predicates to the DocumentRevisionUpdate builder.
func (_u *DocumentRevisionUpdateOne) Where(ps ...predicate.DocumentRevision) *DocumentRevisionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DocumentRevisionUpdateOne) Select(field string, fields ...string) *DocumentRevisionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DocumentRevision entity.
func (_u *DocumentRevisionUpdateOne) Save(ctx context.Context) (*DocumentRevision, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentRevisionUpdateOne) SaveX(ctx context.Context) *DocumentRevision {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DocumentRevisionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentRevisionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentRevisionUpdateOne) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := documentrevision.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "DocumentRevision.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := documentrevision.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DocumentRevision.status": %w`, err)}
		}
	}
	if _u.mutation.DocumentCleared() && len(_u.mutation.DocumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentRevision.document"`)
	}
	if _u.mutation.EditorCleared() && len(_u.mutation.EditorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentRevision.editor"`)
	}
	return nil
}

func (_u *DocumentRevisionUpdateOne) sqlSave(ctx context.Context) (_node *DocumentRevision, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(documentrevision.Table, documentrevision.Columns, sqlgraph.NewFieldSpec(documentrevision.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DocumentRevision.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, documentrevision.FieldID)
		for _, f := range fields {
			if !documentrevision.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != documentrevision.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(documentrevision.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(documentrevision.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(documentrevision.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(documentrevision.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(documentrevision.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Excerpt(); ok {
		_spec.SetField(documentrevision.FieldExcerpt, field.TypeString, value)
	}
	if _u.mutation.ExcerptCleared() {
		_spec.ClearField(documentrevision.FieldExcerpt, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(documentrevision.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(documentrevision.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.DocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentrevision.DocumentTable,
			Columns: []string{documentrevision.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentrevision.DocumentTable,
			Columns: []string{documentrevision.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EditorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentrevision.EditorTable,
			Columns: []string{documentrevision.EditorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EditorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentrevision.EditorTable,
			Columns: []string{documentrevision.EditorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DocumentRevision{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{documentrevision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
