// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shirone-platform/backend/ent/mediaasset"
	"github.com/shirone-platform/backend/ent/predicate"
	"github.com/shirone-platform/backend/ent/user"
)

// MediaAssetUpdate is the builder for updating MediaAsset entities.
type MediaAssetUpdate struct {
	config
	hooks    []Hook
	mutation *MediaAssetMutation
}

// Where appends a list predicates to the MediaAssetUpdate builder.
func (_u *MediaAssetUpdate) Where(ps ...predicate.MediaAsset) *MediaAssetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *MediaAssetUpdate) SetKey(v string) *MediaAssetUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableKey(v *string) *MediaAssetUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetOriginalName sets the "original_name" field.
func (_u *MediaAssetUpdate) SetOriginalName(v string) *MediaAssetUpdate {
	_u.mutation.SetOriginalName(v)
	return _u
}

// SetNillableOriginalName sets the "original_name" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableOriginalName(v *string) *MediaAssetUpdate {
	if v != nil {
		_u.SetOriginalName(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *MediaAssetUpdate) SetMimeType(v string) *MediaAssetUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableMimeType(v *string) *MediaAssetUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *MediaAssetUpdate) SetSize(v int64) *MediaAssetUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableSize(v *int64) *MediaAssetUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *MediaAssetUpdate) AddSize(v int64) *MediaAssetUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetChecksum sets the "checksum" field.
func (_u *MediaAssetUpdate) SetChecksum(v string) *MediaAssetUpdate {
	_u.mutation.SetChecksum(v)
	return _u
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableChecksum(v *string) *MediaAssetUpdate {
	if v != nil {
		_u.SetChecksum(*v)
	}
	return _u
}

// SetAltText sets the "alt_text" field.
func (_u *MediaAssetUpdate) SetAltText(v string) *MediaAssetUpdate {
	_u.mutation.SetAltText(v)
	return _u
}

// SetNillableAltText sets the "alt_text" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableAltText(v *string) *MediaAssetUpdate {
	if v != nil {
		_u.SetAltText(*v)
	}
	return _u
}

// ClearAltText clears the value of the "alt_text" field.
func (_u *MediaAssetUpdate) ClearAltText() *MediaAssetUpdate {
	_u.mutation.ClearAltText()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *MediaAssetUpdate) SetCreatedAt(v time.Time) *MediaAssetUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableCreatedAt(v *time.Time) *MediaAssetUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *MediaAssetUpdate) SetOwnerID(id int) *MediaAssetUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *MediaAssetUpdate) SetOwner(v *User) *MediaAssetUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the MediaAssetMutation object of the builder.
func (_u *MediaAssetUpdate) Mutation() *MediaAssetMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *MediaAssetUpdate) ClearOwner() *MediaAssetUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaAssetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaAssetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaAssetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaAssetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaAssetUpdate) check() error {
	if v, ok := _u.mutation.Size(); ok {
		if err := mediaasset.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.size": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MediaAsset.owner"`)
	}
	return nil
}

func (_u *MediaAssetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaasset.Table, mediaasset.Columns, sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(mediaasset.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalName(); ok {
		_spec.SetField(mediaasset.FieldOriginalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(mediaasset.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(mediaasset.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(mediaasset.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Checksum(); ok {
		_spec.SetField(mediaasset.FieldChecksum, field.TypeString, value)
	}
	if value, ok := _u.mutation.AltText(); ok {
		_spec.SetField(mediaasset.FieldAltText, field.TypeString, value)
	}
	if _u.mutation.AltTextCleared() {
		_spec.ClearField(mediaasset.FieldAltText, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(mediaasset.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaasset.OwnerTable,
			Columns: []string{mediaasset.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaasset.OwnerTable,
			Columns: []string{mediaasset.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaAssetUpdateOne is the builder for updating a single MediaAsset entity.
type MediaAssetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaAssetMutation
}

// SetKey sets the "key" field.
func (_u *MediaAssetUpdateOne) SetKey(v string) *MediaAssetUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableKey(v *string) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetOriginalName sets the "original_name" field.
func (_u *MediaAssetUpdateOne) SetOriginalName(v string) *MediaAssetUpdateOne {
	_u.mutation.SetOriginalName(v)
	return _u
}

// SetNillableOriginalName sets the "original_name" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableOriginalName(v *string) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetOriginalName(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *MediaAssetUpdateOne) SetMimeType(v string) *MediaAssetUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableMimeType(v *string) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *MediaAssetUpdateOne) SetSize(v int64) *MediaAssetUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableSize(v *int64) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *MediaAssetUpdateOne) AddSize(v int64) *MediaAssetUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetChecksum sets the "checksum" field.
func (_u *MediaAssetUpdateOne) SetChecksum(v string) *MediaAssetUpdateOne {
	_u.mutation.SetChecksum(v)
	return _u
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableChecksum(v *string) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetChecksum(*v)
	}
	return _u
}

// SetAltText sets the "alt_text" field.
func (_u *MediaAssetUpdateOne) SetAltText(v string) *MediaAssetUpdateOne {
	_u.mutation.SetAltText(v)
	return _u
}

// SetNillableAltText sets the "alt_text" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableAltText(v *string) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetAltText(*v)
	}
	return _u
}

// ClearAltText clears the value of the "alt_text" field.
func (_u *MediaAssetUpdateOne) ClearAltText() *MediaAssetUpdateOne {
	_u.mutation.ClearAltText()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *MediaAssetUpdateOne) SetCreatedAt(v time.Time) *MediaAssetUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableCreatedAt(v *time.Time) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *MediaAssetUpdateOne) SetOwnerID(id int) *MediaAssetUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *MediaAssetUpdateOne) SetOwner(v *User) *MediaAssetUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the MediaAssetMutation object of the builder.
func (_u *MediaAssetUpdateOne) Mutation() *MediaAssetMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *MediaAssetUpdateOne) ClearOwner() *MediaAssetUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the MediaAssetUpdate builder.
func (_u *MediaAssetUpdateOne) Where(ps ...predicate.MediaAsset) *MediaAssetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaAssetUpdateOne) Select(field string, fields ...string) *MediaAssetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaAsset entity.
func (_u *MediaAssetUpdateOne) Save(ctx context.Context) (*MediaAsset, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaAssetUpdateOne) SaveX(ctx context.Context) *MediaAsset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaAssetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaAssetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaAssetUpdateOne) check() error {
	if v, ok := _u.mutation.Size(); ok {
		if err := mediaasset.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.size": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MediaAsset.owner"`)
	}
	return nil
}

func (_u *MediaAssetUpdateOne) sqlSave(ctx context.Context) (_node *MediaAsset, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaasset.Table, mediaasset.Columns, sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaAsset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediaasset.FieldID)
		for _, f := range fields {
			if !mediaasset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediaasset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(mediaasset.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalName(); ok {
		_spec.SetField(mediaasset.FieldOriginalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(mediaasset.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(mediaasset.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(mediaasset.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Checksum(); ok {
		_spec.SetField(mediaasset.FieldChecksum, field.TypeString, value)
	}
	if value, ok := _u.mutation.AltText(); ok {
		_spec.SetField(mediaasset.FieldAltText, field.TypeString, value)
	}
	if _u.mutation.AltTextCleared() {
		_spec.ClearField(mediaasset.FieldAltText, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(mediaasset.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaasset.OwnerTable,
			Columns: []string{mediaasset.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaasset.OwnerTable,
			Columns: []string{mediaasset.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MediaAsset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
