// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shirone-platform/backend/ent/mediaasset"
	"github.com/shirone-platform/backend/ent/user"
)

// MediaAssetCreate is the builder for creating a MediaAsset entity.
type MediaAssetCreate struct {
	config
	mutation *MediaAssetMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *MediaAssetCreate) SetKey(v string) *MediaAssetCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetOriginalName sets the "original_name" field.
func (_c *MediaAssetCreate) SetOriginalName(v string) *MediaAssetCreate {
	_c.mutation.SetOriginalName(v)
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *MediaAssetCreate) SetMimeType(v string) *MediaAssetCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetSize sets the "size" field.
func (_c *MediaAssetCreate) SetSize(v int64) *MediaAssetCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetChecksum sets the "checksum" field.
func (_c *MediaAssetCreate) SetChecksum(v string) *MediaAssetCreate {
	_c.mutation.SetChecksum(v)
	return _c
}

// SetAltText sets the "alt_text" field.
func (_c *MediaAssetCreate) SetAltText(v string) *MediaAssetCreate {
	_c.mutation.SetAltText(v)
	return _c
}

// SetNillableAltText sets the "alt_text" field if the given value is not nil.
func (_c *MediaAssetCreate) SetNillableAltText(v *string) *MediaAssetCreate {
	if v != nil {
		_c.SetAltText(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MediaAssetCreate) SetCreatedAt(v time.Time) *MediaAssetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *MediaAssetCreate) SetOwnerID(id int) *MediaAssetCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *MediaAssetCreate) SetOwner(v *User) *MediaAssetCreate {
	return _c.SetOwnerID(v.ID)
}

// Mutation returns the MediaAssetMutation object of the builder.
func (_c *MediaAssetCreate) Mutation() *MediaAssetMutation {
	return _c.mutation
}

// Save creates the MediaAsset in the database.
func (_c *MediaAssetCreate) Save(ctx context.Context) (*MediaAsset, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MediaAssetCreate) SaveX(ctx context.Context) *MediaAsset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaAssetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaAssetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MediaAssetCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "MediaAsset.key"`)}
	}
	if _, ok := _c.mutation.OriginalName(); !ok {
		return &ValidationError{Name: "original_name", err: errors.New(`ent: missing required field "MediaAsset.original_name"`)}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "MediaAsset.mime_type"`)}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "MediaAsset.size"`)}
	}
	if v, ok := _c.mutation.Size(); ok {
		if err := mediaasset.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Checksum(); !ok {
		return &ValidationError{Name: "checksum", err: errors.New(`ent: missing required field "MediaAsset.checksum"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MediaAsset.created_at"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "MediaAsset.owner"`)}
	}
	return nil
}

func (_c *MediaAssetCreate) sqlSave(ctx context.Context) (*MediaAsset, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MediaAssetCreate) createSpec() (*MediaAsset, *sqlgraph.CreateSpec) {
	var (
		_node = &MediaAsset{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mediaasset.Table, sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(mediaasset.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.OriginalName(); ok {
		_spec.SetField(mediaasset.FieldOriginalName, field.TypeString, value)
		_node.OriginalName = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(mediaasset.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(mediaasset.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Checksum(); ok {
		_spec.SetField(mediaasset.FieldChecksum, field.TypeString, value)
		_node.Checksum = value
	}
	if value, ok := _c.mutation.AltText(); ok {
		_spec.SetField(mediaasset.FieldAltText, field.TypeString, value)
		_node.AltText = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mediaasset.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaasset.OwnerTable,
			Columns: []string{mediaasset.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_media_assets = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MediaAssetCreateBulk is the builder for creating many MediaAsset entities in bulk.
type MediaAssetCreateBulk struct {
	config
	err      error
	builders []*MediaAssetCreate
}

// Save creates the MediaAsset entities in the database.
func (_c *MediaAssetCreateBulk) Save(ctx context.Context) ([]*MediaAsset, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MediaAsset, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediaAssetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MediaAssetCreateBulk) SaveX(ctx context.Context) []*MediaAsset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaAssetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaAssetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
