// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/shirone-platform/backend/ent/documentrevision"
	"github.com/shirone-platform/backend/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	documentFields := schema.Document{}.Fields()
	_ = documentFields
	documentrevisionFields := schema.DocumentRevision{}.Fields()
	_ = documentrevisionFields
	// documentrevisionDescVersion is the schema descriptor for version field.
	documentrevisionDescVersion := documentrevisionFields[0].Descriptor()
	// documentrevision.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	documentrevision.VersionValidator = documentrevisionDescVersion.Validators[0].(func(int) error)
	// documentrevisionDescTermIds is the schema descriptor for term_ids field.
	documentrevisionDescTermIds := documentrevisionFields[5].Descriptor()
	// documentrevision.DefaultTermIds holds the default value on creation for the term_ids field.
	documentrevision.DefaultTermIds = documentrevisionDescTermIds.Default.([]int)
	userFields := schema.User{}.Fields()
	_ = userFields
}
