// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/shirone-platform/backend/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	documentFields := schema.Document{}.Fields()
	_ = documentFields
	userFields := schema.User{}.Fields()
	_ = userFields
}
