// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shirone-platform/backend/ent/predicate"
	"github.com/shirone-platform/backend/ent/taxonomy"
	"github.com/shirone-platform/backend/ent/term"
)

// TaxonomyUpdate is the builder for updating Taxonomy entities.
type TaxonomyUpdate struct {
	config
	hooks    []Hook
	mutation *TaxonomyMutation
}

// Where appends a list predicates to the TaxonomyUpdate builder.
func (_u *TaxonomyUpdate) Where(ps ...predicate.Taxonomy) *TaxonomyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *TaxonomyUpdate) SetKey(v string) *TaxonomyUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *TaxonomyUpdate) SetNillableKey(v *string) *TaxonomyUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TaxonomyUpdate) SetName(v string) *TaxonomyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TaxonomyUpdate) SetNillableName(v *string) *TaxonomyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaxonomyUpdate) SetDescription(v string) *TaxonomyUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaxonomyUpdate) SetNillableDescription(v *string) *TaxonomyUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaxonomyUpdate) ClearDescription() *TaxonomyUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TaxonomyUpdate) SetCreatedAt(v time.Time) *TaxonomyUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TaxonomyUpdate) SetNillableCreatedAt(v *time.Time) *TaxonomyUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaxonomyUpdate) SetUpdatedAt(v time.Time) *TaxonomyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *TaxonomyUpdate) SetNillableUpdatedAt(v *time.Time) *TaxonomyUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddTermIDs adds the "terms" edge to the Term entity by IDs.
func (_u *TaxonomyUpdate) AddTermIDs(ids ...int) *TaxonomyUpdate {
	_u.mutation.AddTermIDs(ids...)
	return _u
}

// AddTerms adds the "terms" edges to the Term entity.
func (_u *TaxonomyUpdate) AddTerms(v ...*Term) *TaxonomyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTermIDs(ids...)
}

// Mutation returns the TaxonomyMutation object of the builder.
func (_u *TaxonomyUpdate) Mutation() *TaxonomyMutation {
	return _u.mutation
}

// ClearTerms clears all "terms" edges to the Term entity.
func (_u *TaxonomyUpdate) ClearTerms() *TaxonomyUpdate {
	_u.mutation.ClearTerms()
	return _u
}

// RemoveTermIDs removes the "terms" edge to Term entities by IDs.
func (_u *TaxonomyUpdate) RemoveTermIDs(ids ...int) *TaxonomyUpdate {
	_u.mutation.RemoveTermIDs(ids...)
	return _u
}

// RemoveTerms removes "terms" edges to Term entities.
func (_u *TaxonomyUpdate) RemoveTerms(v ...*Term) *TaxonomyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTermIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaxonomyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaxonomyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaxonomyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaxonomyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TaxonomyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(taxonomy.Table, taxonomy.Columns, sqlgraph.NewFieldSpec(taxonomy.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(taxonomy.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(taxonomy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(taxonomy.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(taxonomy.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(taxonomy.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(taxonomy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TermsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taxonomy.TermsTable,
			Columns: []string{taxonomy.TermsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(term.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTermsIDs(); len(nodes) > 0 && !_u.mutation.TermsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taxonomy.TermsTable,
			Columns: []string{taxonomy.TermsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(term.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TermsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taxonomy.TermsTable,
			Columns: []string{taxonomy.TermsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(term.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taxonomy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaxonomyUpdateOne is the builder for updating a single Taxonomy entity.
type TaxonomyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaxonomyMutation
}

// SetKey sets the "key" field.
func (_u *TaxonomyUpdateOne) SetKey(v string) *TaxonomyUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *TaxonomyUpdateOne) SetNillableKey(v *string) *TaxonomyUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TaxonomyUpdateOne) SetName(v string) *TaxonomyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TaxonomyUpdateOne) SetNillableName(v *string) *TaxonomyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaxonomyUpdateOne) SetDescription(v string) *TaxonomyUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaxonomyUpdateOne) SetNillableDescription(v *string) *TaxonomyUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaxonomyUpdateOne) ClearDescription() *TaxonomyUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TaxonomyUpdateOne) SetCreatedAt(v time.Time) *TaxonomyUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TaxonomyUpdateOne) SetNillableCreatedAt(v *time.Time) *TaxonomyUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaxonomyUpdateOne) SetUpdatedAt(v time.Time) *TaxonomyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *TaxonomyUpdateOne) SetNillableUpdatedAt(v *time.Time) *TaxonomyUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddTermIDs adds the "terms" edge to the Term entity by IDs.
func (_u *TaxonomyUpdateOne) AddTermIDs(ids ...int) *TaxonomyUpdateOne {
	_u.mutation.AddTermIDs(ids...)
	return _u
}

// AddTerms adds the "terms" edges to the Term entity.
func (_u *TaxonomyUpdateOne) AddTerms(v ...*Term) *TaxonomyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTermIDs(ids...)
}

// Mutation returns the TaxonomyMutation object of the builder.
func (_u *TaxonomyUpdateOne) Mutation() *TaxonomyMutation {
	return _u.mutation
}

// ClearTerms clears all "terms" edges to the Term entity.
func (_u *TaxonomyUpdateOne) ClearTerms() *TaxonomyUpdateOne {
	_u.mutation.ClearTerms()
	return _u
}

// RemoveTermIDs removes the "terms" edge to Term entities by IDs.
func (_u *TaxonomyUpdateOne) RemoveTermIDs(ids ...int) *TaxonomyUpdateOne {
	_u.mutation.RemoveTermIDs(ids...)
	return _u
}

// RemoveTerms removes "terms" edges to Term entities.
func (_u *TaxonomyUpdateOne) RemoveTerms(v ...*Term) *TaxonomyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTermIDs(ids...)
}

// Where appends a list predicates to the TaxonomyUpdate builder.
func (_u *TaxonomyUpdateOne) Where(ps ...predicate.Taxonomy) *TaxonomyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaxonomyUpdateOne) Select(field string, fields ...string) *TaxonomyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Taxonomy entity.
func (_u *TaxonomyUpdateOne) Save(ctx context.Context) (*Taxonomy, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaxonomyUpdateOne) SaveX(ctx context.Context) *Taxonomy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaxonomyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaxonomyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TaxonomyUpdateOne) sqlSave(ctx context.Context) (_node *Taxonomy, err error) {
	_spec := sqlgraph.NewUpdateSpec(taxonomy.Table, taxonomy.Columns, sqlgraph.NewFieldSpec(taxonomy.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Taxonomy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taxonomy.FieldID)
		for _, f := range fields {
			if !taxonomy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != taxonomy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(taxonomy.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(taxonomy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(taxonomy.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(taxonomy.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(taxonomy.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(taxonomy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TermsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taxonomy.TermsTable,
			Columns: []string{taxonomy.TermsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(term.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTermsIDs(); len(nodes) > 0 && !_u.mutation.TermsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taxonomy.TermsTable,
			Columns: []string{taxonomy.TermsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(term.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TermsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taxonomy.TermsTable,
			Columns: []string{taxonomy.TermsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(term.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Taxonomy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taxonomy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
