// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "body", Type: field.TypeString, Size: 2147483647},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "approved", "rejected"}, Default: "pending"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "comment_replies", Type: field.TypeInt, Nullable: true},
		{Name: "document_comments", Type: field.TypeInt},
		{Name: "user_comments", Type: field.TypeInt},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "comments_comments_replies",
				Columns:    []*schema.Column{CommentsColumns[5]},
				RefColumns: []*schema.Column{CommentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "comments_documents_comments",
				Columns:    []*schema.Column{CommentsColumns[6]},
				RefColumns: []*schema.Column{DocumentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "comments_users_comments",
				Columns:    []*schema.Column{CommentsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// DocumentsColumns holds the columns for the "documents" table.
	DocumentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "slug", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "body", Type: field.TypeString, Size: 2147483647},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "published", "archived"}, Default: "draft"},
		{Name: "excerpt", Type: field.TypeString, Nullable: true},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_documents", Type: field.TypeInt},
	}
	// DocumentsTable holds the schema information for the "documents" table.
	DocumentsTable = &schema.Table{
		Name:       "documents",
		Columns:    DocumentsColumns,
		PrimaryKey: []*schema.Column{DocumentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "documents_users_documents",
				Columns:    []*schema.Column{DocumentsColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "document_slug",
				Unique:  true,
				Columns: []*schema.Column{DocumentsColumns[1]},
			},
			{
				Name:    "document_status",
				Unique:  false,
				Columns: []*schema.Column{DocumentsColumns[4]},
			},
		},
	}
	// DocumentRevisionsColumns holds the columns for the "document_revisions" table.
	DocumentRevisionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "version", Type: field.TypeInt},
		{Name: "slug", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "body", Type: field.TypeString, Size: 2147483647},
		{Name: "excerpt", Type: field.TypeString, Nullable: true},
		{Name: "term_ids", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "published", "archived"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "document_revisions", Type: field.TypeInt},
		{Name: "user_revisions", Type: field.TypeInt},
	}
	// DocumentRevisionsTable holds the schema information for the "document_revisions" table.
	DocumentRevisionsTable = &schema.Table{
		Name:       "document_revisions",
		Columns:    DocumentRevisionsColumns,
		PrimaryKey: []*schema.Column{DocumentRevisionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "document_revisions_documents_revisions",
				Columns:    []*schema.Column{DocumentRevisionsColumns[9]},
				RefColumns: []*schema.Column{DocumentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "document_revisions_users_revisions",
				Columns:    []*schema.Column{DocumentRevisionsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "documentrevision_version_document_revisions",
				Unique:  true,
				Columns: []*schema.Column{DocumentRevisionsColumns[1], DocumentRevisionsColumns[9]},
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_sessions", Type: field.TypeInt},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TaxonomiesColumns holds the columns for the "taxonomies" table.
	TaxonomiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TaxonomiesTable holds the schema information for the "taxonomies" table.
	TaxonomiesTable = &schema.Table{
		Name:       "taxonomies",
		Columns:    TaxonomiesColumns,
		PrimaryKey: []*schema.Column{TaxonomiesColumns[0]},
	}
	// TermsColumns holds the columns for the "terms" table.
	TermsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "slug", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "taxonomy_terms", Type: field.TypeInt},
	}
	// TermsTable holds the schema information for the "terms" table.
	TermsTable = &schema.Table{
		Name:       "terms",
		Columns:    TermsColumns,
		PrimaryKey: []*schema.Column{TermsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "terms_taxonomies_terms",
				Columns:    []*schema.Column{TermsColumns[6]},
				RefColumns: []*schema.Column{TaxonomiesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "term_slug_taxonomy_terms",
				Unique:  true,
				Columns: []*schema.Column{TermsColumns[1], TermsColumns[6]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"member", "editor", "admin"}, Default: "member"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled", "pending"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_status",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[6]},
			},
		},
	}
	// DocumentTermsColumns holds the columns for the "document_terms" table.
	DocumentTermsColumns = []*schema.Column{
		{Name: "document_id", Type: field.TypeInt},
		{Name: "term_id", Type: field.TypeInt},
	}
	// DocumentTermsTable holds the schema information for the "document_terms" table.
	DocumentTermsTable = &schema.Table{
		Name:       "document_terms",
		Columns:    DocumentTermsColumns,
		PrimaryKey: []*schema.Column{DocumentTermsColumns[0], DocumentTermsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "document_terms_document_id",
				Columns:    []*schema.Column{DocumentTermsColumns[0]},
				RefColumns: []*schema.Column{DocumentsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "document_terms_term_id",
				Columns:    []*schema.Column{DocumentTermsColumns[1]},
				RefColumns: []*schema.Column{TermsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CommentsTable,
		DocumentsTable,
		DocumentRevisionsTable,
		SessionsTable,
		TaxonomiesTable,
		TermsTable,
		UsersTable,
		DocumentTermsTable,
	}
)

func init() {
	CommentsTable.ForeignKeys[0].RefTable = CommentsTable
	CommentsTable.ForeignKeys[1].RefTable = DocumentsTable
	CommentsTable.ForeignKeys[2].RefTable = UsersTable
	DocumentsTable.ForeignKeys[0].RefTable = UsersTable
	DocumentRevisionsTable.ForeignKeys[0].RefTable = DocumentsTable
	DocumentRevisionsTable.ForeignKeys[1].RefTable = UsersTable
	SessionsTable.ForeignKeys[0].RefTable = UsersTable
	TermsTable.ForeignKeys[0].RefTable = TaxonomiesTable
	DocumentTermsTable.ForeignKeys[0].RefTable = DocumentsTable
	DocumentTermsTable.ForeignKeys[1].RefTable = TermsTable
}
